$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: ./src
command: >-
  python train_azure.py
  --data_path ${{inputs.dataset}}
  --freeze_backbone
  --epochs 50
  --batch_size 32
  --learning_rate 0.001
  --augment
inputs:
  dataset:
    type: uri_folder
    path: https://cloudholedetec8980605995.blob.core.windows.net/gold/dataset_versions/v1.0_baseline_no_augmentation
environment: azureml:cloud-detector-env:1
compute: azureml:test-cloudhole-cluster
display_name: cloud-hole-training