$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: training
command: >-
  python train.py
  --data_path ${{inputs.dataset}}
  --freeze_backbone
  --epochs 50
  --batch_size 32
  --learning_rate 0.001
  --augment
inputs:
  dataset:
    type: uri_folder
    path: azureml://datastores/gold/paths/datasets/v1.0_baseline
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
compute: azureml:test-cloudhole-cluster
display_name: cloud-hole-training